### PR TITLE
Fix switch animation on first open

### PR DESCRIPTION
**Pull request by lenemter**
Fixes an issue when the switch plays an animation on first opening

It would be great if it was merged before #242

### CODE REVIEW

**Comment by zeebok** [comment]
I can't seem to reproduce this bug you're fixing. This is for the volume mute switch when you open the sound indicator right?

**Comment by jeremypw** [comment]
I think the issue is reproduced as follows:
* Mute sound
* Logout
* Login
* Click on (muted) indicator
* The switch animates to active (unmute)

With this PR, the switch remains muted if the sound was muted when logged out.

**Comment by jeremypw** [comment]
Possibly it was intentional that the muted state should not persist after logging out? If that was the case then the indicator should already be active after logging in.

**Comment by lenemter** [comment]
The issue this PR solves:

https://user-images.githubusercontent.com/80143868/197371255-ed487da1-4903-481b-b36b-956711aa2f91.mp4

You can see switches animate their background color when popup opens for the first time.

@jeremypw didn't notice this issue before, but this branch seems to fix it.

**Comment by lenemter** [comment]
> Possibly it was intentional that the muted state should not persist after logging out? If that was the case then the indicator should already be active after logging in.

It's not intentional since this "feature" appeared after https://github.com/elementary/wingpanel-indicator-sound/pull/235 and I didn't add it on purpose

**Comment by zeebok** [comment]
Hm alright, I have never seen that but if this fixes a regression then great

**Review by zeebok — APPROVED** [review]

**Pull request merged**
