### PR TITLE
Output Device Selector

### LINKED ISSUE #87: Switching output devices [$15]
Can you make switching output devices? In volume indicator menu. 

<bountysource-plugin>

---
There is a **[$15 open bounty](https://www.bountysource.com/issues/65993583-switching-output-devices?utm_campaign=plugin&utm_content=tracker%2F59755748&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59755748&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by DropsOfSerenity**
This pull request adds an output selector to the wingpanel sound dropdown if there are **more than 1** output device currently registered. The devices add/remove properly if they are plugged/unplugged, and default hook changes are there too.

It is **incomplete** I am mainly making this to gauge interest and get designer feedback. A few things that would need to be cleaned up before merge

* I pulled `PulseAudioManager.vala` directly from the switchboard sound plug, we would want a much more minimal version of that as we don't need all the functionality.
* Input Devices should have a selector too.
* ~~Icons need to have a better/more reliable way of getting them, `form_factor` does not appear to work (I don't know much about pulseaudio)~~
* General code cleanup as this was a super **scratch my own itch** poopy code edit, so if it were to be on the track to be merged I would spend more time on it.

Screen record from 2020-08-10 21 06 01

Please let me know what you think and whether this is a feature you all would want in mainline.

This PR would Fix #87 when completed.

### CODE REVIEW

**Comment by DropsOfSerenity** [comment]
Some better icons for different devices.

image

**Comment by DropsOfSerenity** [comment]
Added a basic expander, updated gif.

**Comment by DropsOfSerenity** [comment]
Added toggler and revealer for animations, anyone know what icon is the right arrow `>` and down arrow `v` used in the gtk expander? I would like to use those here.

**Comment by danrabbit** [comment]
Hey sorry for taking a while to reply here! This is really awesome and it would be great to have this feature merged. I don't have a ton of thoughts on the design at the moment. I think we could get the feature merged and iterate as needed :)

**Comment by danrabbit** [comment]
Actually looking at it for a few seconds, I wonder if we need the revealer at all.

Screenshot from 2020-09-25 16 41 58@2x

I think with separators in the right spots we don't need the header text and it's clear that these options belong to the output

I guess we should switch the order of the display name so it's "Device: output type" instead of the other way around.

**Comment by danrabbit** [comment]
It was brought up in Slack that pulseaudio has a priority for device profiles. So in the indicator, it could be a lot cleaner to only show the highest priority profile for each device. That would give us a much shorter list for quickly switching devices here and then we could leave the more advanced choices to System Settings

**Comment by hanaral** [comment]
@DropsOfSerenity Are you able to update the PR with Daniel's suggestions? The design otherwise looks pretty complete...

**Comment by bluesabre** [comment]
I've implemented Daniel's suggestions on #187.

**Comment by danrabbit** [comment]
Closing since #187 was merged

**Pull request closed without merging**
