### PR TITLE
PulseAudioManager: icon fall back to device form factor

### PR DESCRIPTION
**Pull request by danirabbit**
This fixes AirPods Pro showing up as "speakers"

### CODE REVIEW

**Review by jeremypw — APPROVED** [review]
Makes sense

**Comment by tintou** [comment]
@danirabbit for a new PR, you might also add support for all the form factors listed here https://github.com/pulseaudio/pulseaudio/blob/7f4d7fcf5f6407913e50604c6195d0d5356195b1/src/pulse/proplist.h#L211

**Comment by danirabbit** [comment]
@tintou thank you! I was trying to find that list. Will do!

**Comment by danirabbit** [comment]
done https://github.com/elementary/wingpanel-indicator-sound/pull/241

**Pull request merged**
