### PR TITLE
Tattletale: look at all input sources, ignore phones

### LINKED ISSUE #103: Microphone tattler detects Bluetooth phone playing music as microphone
This happens because according to `pavucontrol`, my phone is an input device and playback is happening through a loopback stream.

Screenshot from 2019-06-30 20-10-34

I thought of filtering out any input devices that are either monitors or owned by `module-bluez5-device`, but I don't know whether that would also break the tattler for Bluetooth microphones.

### PR DESCRIPTION
**Pull request by GranPC**
Fixes #103

### CODE REVIEW

**Comment by cassidyjames** [comment]
This appears to work, but I'd like someone more familiar with the code and/or Pulse to take a look before approving.

**Comment by GranPC** [comment]
Actually do not merge - it doesn't look at all input sources, only the last one in the list. Will fix.

**Comment by cassidyjames** [comment]
@GranPC were you still planning to push to this branch? It sounds like a good fix and I'd like to get it in if possible. :)

**Comment by GranPC** [comment]
Yes, I actually intend to get back to this soon! I got tied up with a lot of work shortly after submitting this PR.

**Comment by jeremypw** [comment]
@GranPC Converting to draft as there is a blocking issue and no recent activity.  You were going to try and get back to this - will that be possible?

**Comment by jeremypw** [comment]
Not sure what that message about running workflows is all about - this does not seem to modify the workflow?

**Comment by cassidyjames** [comment]
@jeremypw it's because @GranPC was a new contributor with this PR, so GitHub requires maintainers to approve running CI as a way to prevent abuse. I've approved it!

**Comment by GranPC** [comment]
Hey, yeah this is something I'd like to get back to, possibly for an update to elementary OS 6.

I do think the approach should be rethought; now that AppCenter is going to be based on Flatpak and portals, there might be a more reliable way to detect which apps are using those portals - the current approach doesn't work in cases where a process without a window is listening in to the microphone.

**Comment by jeremypw** [comment]
I think this can be closed now as now recent activity and new approach contemplated.

**Pull request closed without merging**
