### PR TITLE
Adjust scroll speed over Scale

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #3

Looks like only scroll direction `Gdk.ScrollDirection.SMOOTH` is triggered over the `Gtk.Scale`, which seems to be triggered more often, but with a delta. This PR uses the delta to adjust the adjusting step.

### CODE REVIEW

**Comment by peteruithoven** [comment]
Also fixes: #31

**Comment by peteruithoven** [comment]
And: #39

**Comment by jeremypw** [comment]
I would merge this with #73 so that all scroll issues can be dealt with in a consistent way.

**Comment by jeremypw** [comment]
See #81 for some other ideas on how to deal with this.

**Comment by jeremypw** [comment]
See #81 for some other ideas on how to deal with this.

**Comment by peteruithoven** [comment]
@jeremypw has this covered with: https://github.com/elementary/wingpanel-indicator-sound/pull/81

**Pull request closed without merging**
